name: release-linux-aarch64

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Run test suite in chroot environment
      uses: pguyot/arm-runner-action@v2
      id: arm_runner_build
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        cpu_info: raspberrypi_zero2_w_arm64_w
        commands: |
          sudo apt-get update && sudo apt-get install -y cmake libssl-dev libsdl-dev libavcodec-dev libavutil-dev libswscale-dev libresample-dev libusrsctp-dev
    
