name: release-linux-aarch64

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     platform: 
    #       - linux/amd64
    #       - linux/arm64

    steps:
    - name: list
      run: apt-cache search aarch64
    - name: install
      run: sudo apt-get install gcc-aarch64-linux-gnu
    - name: test check
      run: whereis aarch64-linux-gnu-gcc
