name: release-linux-aarch64

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3

    - name: 下载submodule源码
      run: mv -f .gitmodules_github .gitmodules && git submodule sync && git submodule update --init

    - name: 下载 SRTP
      uses: actions/checkout@v2
      with:
        repository: cisco/libsrtp
        fetch-depth: 1
        ref: v2.3.0
        path: 3rdpart/libsrtp

    - name: ls
      run: ls .

    - name: Run Build ARM lib in chroot environment
      uses: pguyot/arm-runner-action@v2
      id: arm_runner_build
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
        image_additional_mb: 1000MB
        commands: |
          sudo apt-get update && sudo apt-get install -y cmake libssl-dev libsdl1.2-dev libavcodec-dev libavutil-dev libswscale-dev libresample-dev libusrsctp-dev
    
