name: release-linux-aarch64

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3

    - name: Run Build ARM lib in chroot environment
      uses: pguyot/arm-runner-action@v2
      id: arm_runner_build
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
        commands: |
          sudo apt-get update && sudo apt-get install -y cmake libssl-dev libsdl1.2-dev libavcodec-dev libavutil-dev libswscale-dev libresample-dev libusrsctp-dev
    
