name: release-linux-aarch64

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     platform: 
    #       - linux/amd64
    #       - linux/arm64

    steps:

    - name: list aarch64 lib
      run: apt-cache search aarch64

    - name: install aarch64 lib
      run: sudo apt-get install gcc-aarch64-linux-gnu

    - name: find the aarch64 gcc
      run: whereis aarch64-linux-gnu-gcc

    - name: ls usr-bin
      run: ls /usr/bin |grep aarch64

    - name: Set CMAKE_C_COMPILER ENV
      run: set CMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc
    - name: Set CMAKE_CXX_COMPILER ENV
      run: set CMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++

    - name: get CMAKE_C_COMPILER
      run: echo $CMAKE_C_COMPILER
